name: Expo CI CD

on:
  push :
    branches : [release, newCalendar, master]

jobs:
  build-for-IOS:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v2

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          # cache: yarn

      - name: ğŸ— Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          # expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          # expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}

      - name: Install deps
        run: yarn install

      - name: Build iOS app
        run: eas build --platform ios --profile staging --non-interactive

  publish-to-testflight:
    needs: [build-for-IOS]
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Setup repo
        uses: actions/checkout@v2

      - name: ğŸ— Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          # cache: yarn

      - name: ğŸ— Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          # expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          # expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
      - name: Install deps
        run: yarn install
      - name: Publish app
        run: eas submit --platform ios --profile staging --non-interactive
